# Generated by Django 5.2.1 on 2025-05-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
